spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        storage_engine: innodb

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/coupon?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul
      username: root
      password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  batch:
    job:
      names: ${job.name:NONE}
      enabled: true
    jdbc:
      initialize-schema: always

  output:
    ansi:
      enabled: always